feat: add abilty to use button as A-tag button with href
PH7-Jack/livewire-ui pull request #172
Opened 2022-01-13 18:52 UTC by REJack

2022-01-24 02:34 UTC, PH7-Jack commented
@REJack Thanks for your contribution. 
I'm making a code review

2022-01-26 05:55 UTC, PH7-Jack requested changes
Thanks for your contribution

2022-01-26 05:55 UTC, PH7-Jack commented on resources/views/components/button.blade.php
> +@if(isset($href))
Don't need to use an if to switch between `a` and `button` tags, just replace the HTML tag
`<{{ $tag }} ..... > .... </{{ $tag }}>`

So, we can use
`<x-button tag="a" href="google.com" .... />`

2022-01-26 05:55 UTC, PH7-Jack commented on src/View/Components/BaseButton.php
> +        $data['href']     = $this->href;
Why did you add it? Don't need to pass the class properties to `$data`
```suggestion
```

2022-01-26 05:55 UTC, PH7-Jack commented on resources/views/components/button.blade.php
> +@if(isset($href))
Add a tag option

2022-01-26 05:55 UTC, PH7-Jack commented on tests/Browser/Button/view.blade.php
> +    <x-button href="#" dark label="dark" icon="home" />
Missing a test to assert if the href can is rendered

2022-01-26 20:31 UTC, REJack commented
I've added a correct test and changed the approach, but without the "tag"-attribute IMHO it's odd and not really needed since you need a `href` for `a`-tags and they will not used on `button`-tags.

2022-02-03 17:39 UTC, bernhardh commented
Would be great, if this could be merged

2022-02-03 18:10 UTC, REJack commented
> Would be great, if this could be merged

Me 2 but I think he will publish his button color changes, before merging my PR 😄 then maybe I would need to add/change stuff

2022-02-15 03:04 UTC, PH7-Jack approved these changes
Thanks for this contribution. Sorry for my long time to review

2022-02-15 03:34 UTC, merged