Feat: Enable feature livewire emit event
PH7-Jack/livewire-ui pull request #209
Opened 2022-02-16 01:14 UTC by putera

This feature resolve issue #178

2022-02-16 01:20 UTC, putera commented
@PH7-Jack why my test is failing. on my local machine its success. please help.

2022-02-16 02:42 UTC, PH7-Jack commented
> @PH7-Jack why my test is failing. on my local machine its success. please help.

Sometimes is needed to re-run the tests, because the dusk breaks with livewire

2022-02-22 03:54 UTC, PH7-Jack commented
@putera what's conflicts do this branch has? don't are showing for me

2022-02-22 04:08 UTC, putera commented
> @putera what's conflicts do this branch has? don't are showing for me

Hi brohter.
I think the conflict because i've modified the TypeScript and need to recompile the js to make sure the test script is working.

- ts/notifications/actions.ts
- ts/notifications/events.ts
- ts/notifications/options.ts
- ts/notifications/parses.ts

2022-02-23 02:46 UTC, PH7-Jack commented
@putera can you merge the main on your branch?

2022-05-06 02:02 UTC, PH7-Jack requested changes
Nice Job, could you fix these two comments for me?

2022-05-06 02:02 UTC, ph7jack commented on tests/Browser/Notifications/view.blade.php
> -    <button
Please, roll back this file. I'm not seeing any changes here

2022-05-06 02:02 UTC, ph7jack commented on ts/notifications/actions.ts
> +  } else if (options.emit) {
```suggestion
  }
  if (options.emit) {
```

2022-05-08 10:55 UTC, putera commented on tests/Browser/Notifications/view.blade.php
> -    <button
Noted.

2022-05-09 00:27 UTC, PH7-Jack approved these changes
Good job @putera

2022-05-09 00:29 UTC, PH7-Jack commented
@putera I recommend you sign your commits. It will be good for all projects that you contribute
https://docs.github.com/pt/authentication/managing-commit-signature-verification/signing-commits

2022-05-09 00:30 UTC, merged