Add wire:target attribute in circle-button component.
PH7-Jack/livewire-ui pull request #242
Opened 2022-04-18 13:33 UTC by raymadrona

When using the `spinner` prop in a `x-button.circle` with multiple instances but with a different target, it removes the icon in the other button instance during the loading state.

For example:

```
<x-button.circle xs primary icon="plus" wire:click="add" spinner="add"/>
<x-button.circle xs warning icon="pencil" wire:click="edit" spinner="edit"/>
```

When the `add` button is clicked, it removes the icon in the `edit` button which should not be cased.

This PR resolves this issue by adding the wire:target attribute as an additional condition when removing the button icon.

2022-05-04 05:37 UTC, PH7-Jack requested changes

2022-05-04 05:37 UTC, PH7-Jack commented on resources/views/components/circle-button.blade.php
> +    <div @if($spinner) wire:target="{{ $spinner }}" wire:loading.remove @endif>
Add a conditional wire target as the button component does

https://github.com/wireui/wireui/blob/main/resources/views/components/button.blade.php#L39

2022-05-04 16:01 UTC, PH7-Jack approved these changes
Nice job @raymadrona. Thank you

2022-05-04 16:23 UTC, merged

2024-06-27 11:14 UTC, Uhasith commented
Still facing this issue with mini buttons.  @raymadrona @PH7-Jack 

``` <x-wui-mini-button rounded secondary icon="plus"wire:click="addSubTask" spinner="addSubTask" x-tooltip.placement.bottom.raw="Add Sub Task" />```

 "wireui/wireui": "^2.0",
  "livewire/livewire": "^3.4"