Drafted : Fix dropdown width and allow notification in html
PH7-Jack/livewire-ui pull request #261
Opened 2022-05-10 07:30 UTC by putera

Dropdown width :

Current Situation :
![](https://i.ibb.co/Pz6ntWM/dropdown-bug.png)

Fixed
![](https://i.ibb.co/dcWcDL5/dropdown-fixed.png)

Notification in HTML - Allow HTML in notification :
![](https://i.ibb.co/60sK5Yp/notification-fixed.png)

2022-05-10 13:20 UTC, PH7-Jack commented
@putera Great feature, mark me when it's ready to merge

2022-05-10 15:39 UTC, putera commented
> @putera Great feature, mark me when it's ready to merge

Will do bro. 👍🏿👍🏿👍🏿

2022-05-22 04:40 UTC, PH7-Jack commented
@putera if you need some help with this feature, you can ask me. This PR is very useful
Thanks bro

2022-05-22 05:23 UTC, putera commented
> @putera if you need some help with this feature, you can ask me. This PR is very useful
> Thanks bro

Ok brother, i will proceed with this first.

2022-05-26 04:53 UTC, PH7-Jack requested changes
Amazing work ❤️ 

Could you fix these comments?

2022-05-26 04:53 UTC, PH7-Jack commented on resources/views/components/button.blade.php
> +        'wire:target' => (strlen($spinner) > 1) ? $spinner : null,
```suggestion
        'wire:loading.attr'  => 'disabled',
        'wire:loading.class' => '!cursor-wait',
        'wire:target'        => (strlen($spinner) > 1) ? $spinner : null,
```

2022-05-26 04:53 UTC, PH7-Jack commented on resources/views/components/dropdown.blade.php
> +        class="{{ $getAlign() }} z-30 absolute mt-2 whitespace-nowrap"
```suggestion
        class="{{ $getAlign() }} z-30 absolute mt-2 {{ $width }} whitespace-nowrap"
```

2022-05-26 04:53 UTC, PH7-Jack commented on src/View/Components/Select.php
> +        public bool $showItemsCount = true,
Could you rename it to **withoutItemsCount**, so we can pass it in an easy way
```suggestion
        public bool $withoutItemsCount = false,
```
`<x-select without-items-count ... />`

2022-05-26 13:43 UTC, PH7-Jack approved these changes
Thanks a lot for contributing

2022-05-26 13:43 UTC, merged