Updated dropdown to make a separate separator with no rounded corners
PH7-Jack/livewire-ui pull request #288
Opened 2022-05-23 11:03 UTC by ettiennelouw

2022-05-26 04:29 UTC, PH7-Jack requested changes
Thanks for your contribution, I liked it
Could you fix these comments?

2022-05-26 04:29 UTC, PH7-Jack commented on src/View/Components/Dropdown/DropdownItem.php
> +    public ?bool $separator;
```suggestion
    public bool $separator;
```

2022-05-26 04:29 UTC, PH7-Jack commented on src/View/Components/Dropdown/DropdownItem.php
> +            // });
remove this block of code

2022-05-26 04:29 UTC, PH7-Jack commented on resources/views/components/dropdown/item.blade.php
> +@if ($separator ?? '')
```suggestion
@if ($separator)
```

2022-05-26 08:09 UTC, ettiennelouw commented
Awsome, oh wow yes sure! Forgot the commented code.

2022-05-27 17:52 UTC, ettiennelouw commented
I have removed the commented code and code changes as requested.

2022-05-28 22:32 UTC, PH7-Jack approved these changes
Great

2022-05-28 22:44 UTC, PH7-Jack commented
@ettiennelouw  I recommend you improve your commits security using the signed commits

https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits

2022-05-28 22:44 UTC, merged