Fix select subcomponents not using unique keys
PH7-Jack/livewire-ui pull request #375
Opened 2022-07-14 10:12 UTC by saulens22

While using `select` component, the `label` and `search-options` sub-components doesn't have unique keys. This leads to situations where multiple `select`s are in a page and clicking on it's label brings up menu on another one, labels randomly disappear, etc. This pull request should fix that.

Thanks @donatiss for helping with fix.

2022-07-14 11:16 UTC, PH7-Jack approved these changes
@saulens22 Very interesting PR, thanks for contributing. I'll merge it soon.
Do you have a Twitter account?

2022-07-14 11:38 UTC, saulens22 commented
Yes I have. It's in my bio.

2022-07-17 00:34 UTC, PH7-Jack requested changes

2022-07-17 00:34 UTC, PH7-Jack commented on resources/views/components/select.blade.php
> +            <div class="px-2 my-2" :wire:key="'search.options.' . $name">
It doesn't will take any effect, remove the ":" in the wire:key attribute
```suggestion
            <div class="px-2 my-2" wire:key="search.options.{{ $name }}">
```

2022-07-17 00:35 UTC, PH7-Jack approved these changes
@saulens22 thanks for contributing

2022-07-17 00:35 UTC, merged