Added avatars and basic options
PH7-Jack/livewire-ui pull request #376
Opened 2022-07-14 10:44 UTC by ettiennelouw

Added avatar components with some basic settings

- Size: xs, sm, md, lg, xl, full
- type: rounded (default), square
- bordered
- text (no image just has text in the center)
- light & dark mode
 
```
<x-avatar/>
<x-avatar xs/>
<x-avatar sm>
    <x-slot name="content">
        <img src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt="">
    </x-slot>
</x-avatar>
<x-avatar md />
<x-avatar lg squared border />
<x-avatar xl />
<x-avatar xl border text>
    <span class="text-md font-medium leading-none text-white">TW</span>
</x-avatar>
<div class="w-96 h-96 border border-red-400">
    <x-avatar full />
</div>
```
<img width="678" alt="Screenshot 2022-07-14 at 12 43 30" src="https://user-images.githubusercontent.com/1754421/178964966-ff3923e8-3b50-482d-a81b-02f8bd4f68c6.png">
<img width="796" alt="Screenshot 2022-07-14 at 12 43 23" src="https://user-images.githubusercontent.com/1754421/178964984-90f99530-5ab0-42bd-8da3-212809fc93b2.png">

2022-07-14 11:12 UTC, PH7-Jack commented
@ettiennelouw Thanks for contributing 😄. I'm reviewing this PR, could you add some tests for this component?

2022-07-14 19:02 UTC, ettiennelouw commented
Added tests for the avatars, if you can please check if that is sufficient.

2022-07-19 04:44 UTC, PH7-Jack requested changes
@ettiennelouw Awesome job

2022-07-19 04:44 UTC, ph7jack commented on src/View/Components/Avatar.php
> +    public ?string $content;
Remove these properties, in the PHP 8+ we can use the property in the constructor method

```suggestion
```

References
https://stitcher.io/blog/constructor-promotion-in-php-8
https://www.php.net/manual/pt_BR/migration80.new-features.php

2022-07-19 04:44 UTC, ph7jack commented on src/View/Components/Avatar.php
> +        string $content = null
```suggestion
        public bool $xs = false,
        public bool $sm = false,
        public bool $md = false,
        public bool $lg = false,
        public bool $xl = false,
        public bool $full = false,
        public bool $squared = false,
        public bool $text = false,
        public ?string $border = 'border border-gray-200 dark:border-secondary-400',
        public ?string $avatarClasses = null,
        public ?string $content = null
```

2022-07-19 04:44 UTC, ph7jack commented on src/View/Components/Avatar.php
> +        string $content = null
The default value doesn't match the allowed type

2022-07-19 04:44 UTC, ph7jack commented on src/View/Components/Avatar.php
> +        $this->content = $content;
```suggestion
        $this->avatarClasses = $this->getAvatarClasses($avatarClasses);
```

2022-07-19 04:44 UTC, ph7jack commented on src/View/Components/Avatar.php
> +    }
1. Rename the method to getAvatarClasses, the setFoo is for setters, this method doesn't set anything
2. Make this class maker simpler, see this link for reference
https://github.com/wireui/wireui/commit/fe901ec37fb6c49900b60e6d2d51a02c1c5bfe08#diff-4de7170a20da3333d2caf090aef938be990114aa3d7b726b0122672fe7645910R29-R36
```
return $this->classes([
    'items-center justify-center overflow-hidden bg-gray-100 dark:bg-secondary-600',
    'inline-flex' => $this->text,
    'inline-block' => !$this->text,
    ...
]);
```

2022-07-19 04:44 UTC, ph7jack commented on src/View/Components/Avatar.php
> +    public function render()
move to below the `__construct` method

2022-07-19 04:44 UTC, ph7jack commented on resources/views/components/avatar.blade.php
> +    {{ $content ?? $slot }}
I think this slot is not needed, it will increase the component complexity.

2022-07-19 04:44 UTC, ph7jack commented on resources/views/components/avatar.blade.php
> +    @if(!$content && $slot->isEmpty())
If the src image is null or the label is null, show the SVG

```suggestion
    @if (!$src || !$label)
```

2022-07-19 04:44 UTC, PH7-Jack commented on resources/views/components/avatar.blade.php
> +    {{ $content ?? $slot }}
We can just pass the props src and label

```
<x-avatar src="link" />
<x-avatar label="PO" />
```

2022-07-19 04:44 UTC, PH7-Jack commented on resources/views/components/avatar.blade.php
> +    {{ $content ?? $slot }}
@ettiennelouw What do you think about it? The avatar component can handle the img or label

2022-07-20 04:29 UTC, ettiennelouw commented on src/View/Components/Avatar.php
> +    public ?string $content;
OH wow, I just learned something new. This has been changed

2022-07-21 12:09 UTC, ettiennelouw commented on resources/views/components/avatar.blade.php
> +    {{ $content ?? $slot }}
I like it, I will do the change

2022-07-21 12:29 UTC, ettiennelouw commented
```
<x-avatar/>
<x-avatar xs/>
<x-avatar sm>
    <x-slot name="src">
        <img src="https://images.unsplash.com/photo-1599566150163-29194dcaad36?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8M3x8YXZhdGFyfGVufDB8fDB8fA%3D%3D&w=1000&q=80" alt="">
    </x-slot>
</x-avatar>
<x-avatar md />
<x-avatar lg squared border />
<x-avatar xl />
<x-avatar xl border label="AB1"/>
<div class="w-96 h-96 border border-red-400">
    <x-avatar full />
</div>
<x-avatar xs avatarClasses="mt-6 ml-6"/>
```

2022-07-24 18:50 UTC, PH7-Jack commented on resources/views/components/avatar.blade.php
> +    {{ $label }}
```suggestion
<span {{ $attributes->class($avatarClasses) }}>
    {{ $label }}
```

2022-07-24 18:50 UTC, PH7-Jack commented on resources/views/components/avatar.blade.php
> +    <img src="{{ $src }}"/>
```suggestion
    @if ($src)
        <img src="{{ $src }}" />
    @endif
```

2022-07-24 18:50 UTC, PH7-Jack commented on src/View/Components/Avatar.php
> +        ]);
@ettiennelouw You should use the php-cs-fixer to format the code

```suggestion
        return $this->classes([
            'items-center justify-center overflow-hidden bg-gray-100 dark:bg-secondary-600',
            'inline-flex'   => $this->label,
            'inline-block'  => !$this->label,
            'w-6 h-6'       => $this->xs,
            'w-8 h-8'       => $this->sm,
            'w-10 h-10'     => $this->md,
            'w-12 h-12'     => $this->lg,
            'w-14 h-14'     => $this->xl,
            'w-full h-full' => $this->full,
            'rounded-md'    => $this->squared,
            'rounded-full'  => !$this->squared,
            $this->border,
        ]);
```

2022-07-24 18:50 UTC, PH7-Jack commented on src/View/Components/Avatar.php
> +    public function getAvatarClasses(?string $avatarClasses): string
```suggestion
    public function getAvatarClasses(): string
```

2022-07-24 18:50 UTC, PH7-Jack commented on src/View/Components/Avatar.php
> +        $this->avatarClasses = $this->getAvatarClasses($avatarClasses);
```suggestion
        public ?string $avatarClasses = null,
    ) {
        $this->avatarClasses = $this->getAvatarClasses();
```

2022-07-24 18:56 UTC, PH7-Jack submitted a review, later dismissed
Great job @ettiennelouw 
![giphy](https://user-images.githubusercontent.com/38913462/180661849-92efcbed-dd3c-4eda-8dd0-6cc50f3c66fd.gif)

2022-07-25 11:35 UTC, ettiennelouw commented
Awsome, Thanks

2022-07-27 05:55 UTC, PH7-Jack approved these changes
@ettiennelouw I have changed some behaviors and styles in this component to make it simple to use and maintain the code. I've added more tests to assert if the component is working in the future. Now I finish the documentation. Thanks

2022-07-27 05:56 UTC, merged