Feature/v2 buttons
PH7-Jack/livewire-ui pull request #570
Opened 2022-12-13 00:59 UTC by PH7-Jack

#### Overview
- Refactor colors
- Refactor Sizes
- Add tests with 100% coverage

#### New Features
- Light Color
- Mini Button: squared, rounded, and circle
- Colors Customization
- Sizes Customization
- Ring Offset color customization
- Multicolor buttons

#### Breaking Changes
- Removed `$loadingDelay` prop, use the spinner attribute instead
- Removed `<x-circle-button />`, use the `<x-buttons.mini />` instead. The mini button can be **rounded** or **squared** 
- Renamed `<x-icon.spinner />` to `<x-wireui::icons.spinner />`
- Removed dark color

2022-12-13 15:25 UTC, joaopalopes24 requested changes

2022-12-13 15:25 UTC, joaopalopes24 commented on src/Support/Buttons/Colors/ColorPack.php
> +        if (!$color || $color === 'default') {
Use ternary:

```
        return !$color || $color === 'default'
            ? $this->default()
            : data_get(
                target: $this->all(),
                key: $color,
                default: new Color($color),
            );
```

2022-12-13 15:25 UTC, joaopalopes24 commented on src/Support/Buttons/Sizes/SizePack.php
> +        if (!$size || $size === 'default') {
Use ternary:

```
        return !$size || $size === 'default'
            ? $this->default()
            : data_get(
                target: $this->all(),
                key: $size,
                default: $size,
            );
```

2022-12-13 15:25 UTC, joaopalopes24 commented on src/View/Attribute.php
> +        if (!str_contains($this->directive, ':')) {
Use ternary:

```
        return str_contains($this->directive, ':')
            ? Str::of($this->directive)->after(':')->before('.')
            : null;
```

2022-12-13 15:25 UTC, joaopalopes24 commented on src/View/Components/Buttons/Base.php
> +        if ($this->attributes->has('href')) {
Use ternary:

`return $this->attributes->has('href') ? 'a' : 'button';`

2022-12-13 15:25 UTC, joaopalopes24 commented on src/config.php
> +        |--------------------------------------------------------------------------
Leave the comment inline as the Laravel default.

2022-12-13 15:25 UTC, joaopalopes24 commented on src/config.php
> +        |--------------------------------------------------------------------------
Leave the comment inline as the Laravel default.

2022-12-14 02:32 UTC, ph7jack commented on src/Support/Buttons/Colors/ColorPack.php
> +        if (!$color || $color === 'default') {
Avoid complex ternary usages to keep the code simple to read.
Use ternary only when you have two simple values and no multiline

2022-12-14 02:59 UTC, merged