Added spinner option to input component.
PH7-Jack/livewire-ui pull request #725
Opened 2023-09-17 18:38 UTC by felipeArnold

Good afternoon, how are you?
I found a need to add a spinner to the input component, in my case I needed to consult an api, with the spinner I can show the user that their request is being consulted.

![image](https://github.com/wireui/wireui/assets/44820260/1218459a-892d-4967-8bc3-90d9cae7e547)

2023-10-18 06:26 UTC, PH7-Jack requested changes
Thanks for contributing, your PR looks good!

2023-10-18 06:26 UTC, PH7-Jack commented on resources/views/components/input.blade.php
> +                </svg>
Add one tab indentation here.

2023-10-18 06:26 UTC, PH7-Jack commented on src/View/Components/Input.php
> +        $this->spinner = $spinner;
Please, use the phpcs fixer to format this file. Wireui is using it for code style.

2023-10-25 05:51 UTC, PH7-Jack requested changes

2023-10-25 05:51 UTC, PH7-Jack commented on resources/views/components/input.blade.php
> +                        @if ($spinner) :wire:loading.remove="(bool) $spinner" @endif
Using directives inside a blade component attributes wont work

2023-11-03 11:44 UTC, PH7-Jack approved these changes
thanks for contributing

2023-11-03 11:45 UTC, merged

2024-03-21 09:14 UTC, dwainscheeren commented
I now get error `Undefined variable $spinner` on using ```<x-input 
                class="w-full" 
                placeholder="Zoeken..." 
                wire:model.live="term"
                type="search" 
                icon="search"
                
            />```